services:
  eventstore:
    image: eventstore/eventstore:22.10.2-alpha-arm64v8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - type: volume
        source: cassandra-volume-data
        target: /var/lib/cassandra
  init:
    image: cassandra:latest
    depends_on:
      - cassandra
    restart: "no"
    entrypoint: [ "/cassandra-init.sh" ]
    volumes:
      - ./cassandra-init.sh:/cassandra-init.sh
volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  cassandra-volume-data:
